#!/usr/bin/env bash
set -euo pipefail

env_verify APP_URL

check_slash_monitoring() {
    url="${APP_URL}/monitoring"

    status=$(curl -sSko /dev/null -w "%{http_code}" "$url")
    response=$(curl -ksS "$url")

    echo "status=$status"
    echo "response=$response"

    [ "$status" -eq 200 ] && [[ ! "$response" =~ "error" ]]
}

max_wait=${max_wait:-60}
wait_for_retry=1

while [[ "$wait_for_retry" -le "$max_wait" ]];
do
    if check_slash_monitoring; then
        exit 0
    else
        sleep $(( wait_for_retry *= 2 ))
    fi
done

exit 1
