#!/usr/bin/env bash
set -euo pipefail

env_verify BUILD_SCRIPTS_DIR GITLAB_TOKEN GITLAB_ENDPOINT PROJECT_NAME GIT_BRANCH GIT_ROOT
bundle_verify gitlab
bundle_verify brakeman

export GITLAB_PROJECT_NAME=${GITLAB_PROJECT_NAME:-${PROJECT_NAME}}
export GITLAB_BRANCH=${GITLAB_BRANCH:-${GIT_BRANCH}}
export GITLAB_PROJECT_URL=$(bundle_exec $BUILD_SCRIPTS_DIR/gitlab-notifiers/project-url.rb)

# get files which have been added or modified between HEAD and origin/master
target_branch=$(bundle_exec $BUILD_SCRIPTS_DIR/gitlab-notifiers/merge-request-destination-branch.rb)
files_to_inspect=$(git diff --diff-filter=AM --name-only $(git merge-base $target_branch HEAD) HEAD | grep '\.rb$')

set +o pipefail
bundle_exec brakeman --format json -p $GIT_ROOT 2>/dev/null \
    | $BUILD_SCRIPTS_DIR/gitlab-notifiers/format-brakeman-report-message.rb \
    | bundle_exec $BUILD_SCRIPTS_DIR/gitlab-notifiers/notify.rb
set -o pipefail
