#!/usr/bin/env bash
set -euo pipefail

env_verify BUILD_SCRIPTS_DIR GITLAB_TOKEN GITLAB_ENDPOINT PROJECT_NAME GIT_BRANCH GIT_ROOT

bundle_verify gitlab
$BUILD_SCRIPTS_DIR/gitlab-notifiers/format-build-status-message.rb \
    | bundle exec $BUILD_SCRIPTS_DIR/gitlab-notifiers/notify.rb
