#!/usr/bin/env bash
set -euo pipefail

env_verify BUILD_SCRIPTS_DIR GITLAB_TOKEN GITLAB_ENDPOINT PROJECT_NAME GIT_BRANCH GIT_ROOT
bundle_verify gitlab

export GITLAB_PROJECT_NAME=${GITLAB_PROJECT_NAME:-${PROJECT_NAME}}
export GITLAB_BRANCH=${GITLAB_BRANCH:-${GIT_BRANCH}}

set +o pipefail
$BUILD_SCRIPTS_DIR/bundle-outdated \
    | awk '
BEGIN { print "### Bundle outdated report: :cop:" }
      { print $0 "\n"}
' \
    | bundle_exec $BUILD_SCRIPTS_DIR/gitlab-notifiers/notify.rb
set -o pipefail
