#!/usr/bin/env bash
set +eo pipefail
set -u

# set up gitlab client
gem list gitlab -i > /dev/null 2>&1 || gem install gitlab --no-ri --no-rdoc

# find config file
if [ -f $GIT_ROOT/.reek ]; then
    config=$GIT_ROOT/.reek
else
    config=$GIT_ROOT/config.reek.example
fi

# get files which have been added or modified between HEAD and origin/master
files_to_inspect=$(git diff --diff-filter=AM --name-only "origin/master" HEAD | grep '\.rb$')

export GITLAB_PROJECT_URL=$("$BUILD_SCRIPTS_DIR/gitlab-notifiers/project-url.rb")
echo $GITLAB_PROJECT_URL
bundle exec reek -c $config --no-color -U $files_to_inspect \
    | $BUILD_SCRIPTS_DIR/gitlab-notifiers/format-reek-report-message.rb \
    | $BUILD_SCRIPTS_DIR/gitlab-notifiers/notify.rb

set -eo pipefail
