#!/usr/bin/env bash
set -euo pipefail

# get files which have been added or modified between HEAD and origin/master
target_branch=$(bundle exec $BUILD_SCRIPTS_DIR/gitlab-notifiers/merge-request-destination-branch.rb)
files_to_inspect=$(git diff --diff-filter=AM --name-only $(git merge-base $target_branch HEAD) HEAD | grep '\.rb$')

# find config file
if [ -f $GIT_ROOT/.reek ]; then
    config=$GIT_ROOT/.reek
else
    config=$GIT_ROOT/config.reek.example
fi

# Set gitlab up
bundle_verify gitlab
bundle_verify reek

export GITLAB_PROJECT_URL=$(bundle exec $BUILD_SCRIPTS_DIR/gitlab-notifiers/project-url.rb)

set +o pipefail
bundle exec reek -c $config --no-color -U $files_to_inspect \
    | $BUILD_SCRIPTS_DIR/gitlab-notifiers/format-reek-report-message.rb \
    | bundle exec $BUILD_SCRIPTS_DIR/gitlab-notifiers/notify.rb
set -o pipefail
