#!/usr/bin/env bash
set -euo pipefail

# get files which have been added or modified between HEAD and origin/master
files_to_inspect=$(git diff --diff-filter=AM --name-only "origin/master" HEAD | grep '\.rb$')

# find config file
if [ -f $GIT_ROOT/.rubocop.yml ]; then
    config=$GIT_ROOT/.rubocop.yml
else
    config=$GIT_ROOT/.rubocop.yml.example
fi

# Set gitlab up
bundle_verify gitlab
bundle_verify rubocop

export GITLAB_PROJECT_URL=$(bundle exec $BUILD_SCRIPTS_DIR/gitlab-notifiers/project-url.rb)

set +o pipefail
bundle exec rubocop -c $config --format json --no-color $files_to_inspect \
    | $BUILD_SCRIPTS_DIR/gitlab-notifiers/format-rubocop-report-message.rb \
    | bundle exec $BUILD_SCRIPTS_DIR/gitlab-notifiers/notify.rb
set -o pipefail
