#!/usr/bin/env bash
set -euo pipefail

echo 'Making sure bundle 1.10.6 is installed...' >&2
(gem list bundler$ | grep "1\.10\.6" || gem install bundler -v 1.10.6 --no-rdoc --no-ri) >&2

echo 'Checking if bundle is up to date...' >&2
[ ! -f outdated.txt ] && bundle outdated > outdated.txt || true

set +o pipefail # grep fails if there is no match! we don't want this here

cat outdated.txt \
    | awk -f $BUILD_SCRIPTS_DIR/bundle-outdated.d/critical.awk \
    | tee outdated_production.txt

cat outdated.txt \
    | awk -f $BUILD_SCRIPTS_DIR/bundle-outdated.d/non-critical.awk \
    | tee outdated_non_production.txt

if [ "$(cat outdated_production.txt | wc -l)" -gt 2 ]; then
    red_echo 'There are outdated gems!!' >&2
    exit 1
fi
set -o pipefail
