#!/usr/bin/env bash
set -euo pipefail

env_verify DEPLOY_PACKAGE_NAME DEPLOY_PACKAGE_HOST

set +u
version=$DEPLOY_PACKAGE_VERSION
default_distro=${DEPLOY_PACKAGE_DISTRO:-stable}
set -u

now() { date +%s ;}

get_distro_for() {
    package=$1
    version=$2

    sudo apt-cache madison "$package" \
        | grep "$version" \
        | awk '{ gsub(/\/main$/, "", $6); print $6 }' \
        | head -n1
}

with_spin_lock() {
    deadline=$(( $(now) + $1 ))
    shift;
    while [[ $(now) -le "$deadline" ]]; do
        red_echo "trying \"$@\" ..."
        { $@ && return 0 ;} || sleep $(( $RANDOM % 10 + 1 ))
    done
    return 1
}

ssh "$DEPLOY_PACKAGE_HOST" <<EOF
$(declare -f now)
$(declare -f with_spin_lock)
$(declare -f get_distro_for)
$(declare -f red_echo)

if [ -n "$version" ]; then
  distro=\$(get_distro_for "$DEPLOY_PACKAGE_NAME" "$version")

  if [ -z "\$distro" ]; then
    red_echo "Couldn't get distro for $version. Calling apt-get update"
    with_spin_lock 180 sudo apt-get update -q
    distro=\$(get_distro_for "$DEPLOY_PACKAGE_NAME" "$version")
  fi

  # break out of the deployment if I can't still find the version
  [ -z "\$distro" ] && red_echo "Can't find version $version" && exit 1
else
  red_echo "Version wasn't set, so we're installing from the distro *${default_distro}*"
  distro=${default_distro}
  with_spin_lock 180 sudo apt-get update -q
fi

  red_echo "finally, calling apt-get install"
  with_spin_lock 180 sudo apt-get install "$DEPLOY_PACKAGE_NAME/\$distro" -y --force-yes
EOF
