#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd $SCRIPT_DIR

GIT_ROOT="$(git rev-parse --show-toplevel)"
cd $GIT_ROOT

git clean -ffdx -e build-scripts -e env.sh.example -e jobs.sh.example
git reset --hard
