#!/usr/bin/env bash
export GEM_DEPENDENCIES_AUTOINSTALL=${GEM_DEPENDENCIES_AUTOINSTALL:-}

red_echo() {
    local txtred='\e[0;31m' # Red
    local clroff='\e[0m' # Text Reset

    echo -e "$txtred$1$clroff"
}
export -f red_echo

with_label() {
    local txtgrn='\e[1;32m' # Green
    local clroff='\e[0m' # Text Reset

    name=$1
    while IFS= read LINE
    do
        echo -e "$txtgrn$name: $clroff$LINE"
    done
}

execute() {
    echo
    red_echo "### Running: $1"
    $BUILD_SCRIPTS_DIR/$1 |& with_label $1
}

ruby_manager_executor() {
    BUNDLE_GEMFILE=/dev/null rvm-exec 2.2.2@ci-scripts $*
}
export -f ruby_manager_executor

bundle_verify() {
    if [[ $GEM_DEPENDENCIES_AUTOINSTALL == "true" ]]
    then
        ruby_manager_executor gem install --conservative $1
    else
        bundle list $1 2>&1 >/dev/null ||
            (red_echo "You must add the $1 gem to your bundle to enjoy all of ci-scripts niceties" >&2 &&
                 exit 1)
    fi
}
export -f bundle_verify

bundle_exec() {
    if [[ $GEM_DEPENDENCIES_AUTOINSTALL == "true" ]]
    then
        ruby_manager_executor $*
    else
        bundle exec $*
    fi
}
export -f bundle_exec

env_verify() {
    error=""
    set +u
    for var in "$@"; do
        [[ ! -v "$var" ]] && error="${error}${var} environment variable is not set\n"
    done
    [ ! -z "$error" ] && { red_echo "$error"; exit 1 ;} || return 0
}
export -f env_verify

bricky() {
    bundle_verify bricky
    bundle_exec bricky version
    bundle_exec bricky $*
}
export -f bricky

# Auto execute gemset create if this feature is enabled
if [[ $GEM_DEPENDENCIES_AUTOINSTALL == "true" ]]
then
    # force environment creation
    ruby_manager_executor rvm current
fi
