#!/usr/bin/env bash
set -xeuo pipefail

RAILS_ENV=test bundle exec rake db:drop db:create db:migrate db:seed
bundle exec rspec spec/ --format documentation

if [[ "$RUN_WITH_VCR_OFF" == "true" ]]; then
    echo '### Running tests with vcr turned off'
    . config/$APP_NAME-env-devint.sh
    RAILS_ENV=test VCR_OFF=true bundle exec rspec spec/
else
    echo -e "\e[0;31m !!!!!!! SKIPPING RSPEC WITH VCR TURNED OFF !!!!!! \033[0m"
fi
