#!/usr/bin/env bash
set -euo pipefail

echo 'Executing brakeman...'
bundle_verify brakeman
bundle_exec brakeman

echo 'Executing bundle-audit...'
bundle_verify bundle-audit
bundle_exec bundle-audit update
bundle_exec bundle-audit check --ignore $BUNDLE_AUDIT_IGNORED_CVES
